### PR TITLE
fix relative path problem

### LINKED ISSUE #7: Ignore pattern doesn't work with relative paths starting with ../
This is a confirmed bug (see https://github.com/facebook/jscodeshift/issues/556), and I think there’s not much we can do except wait for the jscodeshift maintainers to fix it.

### PR DESCRIPTION
**Pull request by bjohansebas**
Solving the relative path would solve this problem with the ignore pattern

Fixes #7

### CODE REVIEW

**Review by kjugi — COMMENTED** [review]
I have applied some changes to the code itself. 
Your change with a fix for a relative path problem is still there. When I started to debug the unit tests I noticed a few more changes and decided to apply them instead of explaining what I meant in the comments. Hope you don't mind ✌️

**Comment by bjohansebas** [comment]
Now there's a small issue with Windows, I'll check it later.

File: commands/transform.ts [hunk 1]
```diff
@@ -67,5 +72,5 @@ export async function transform(codemodName?: string, source?: string, options?:
     extensions: 'cts,mts,ts,js,mjs,cjs',
   }
 
-  await jscodeshift(transformerPath, [sourceSelected || ''], args)
+  await jscodeshift(transformerPath, [resolve(sourceSelected)], args)
```
Comment (kjugi) [inline commands/transform.ts:75]: I'm doing `resolve` for `sourceSelected` in line 58. I will revert this change

**Review by kjugi — APPROVED** [review]
